### ISSUE TITLE
entries in words.txt are not delimited by new lines

### ISSUE THREAD

**Issue by Starless2001** [dwyl/english-words#2]
All words make up one giant line without even spaces between each other.

**Comment by nelsonic** [comment]
@Starless2001 are you referring to https://raw.githubusercontent.com/dwyl/english-words/master/words.txt ?
How are you viewing the `.txt` file? (*it should be one word per line...*)

**Comment by Starless2001** [comment]
When visualised with windows notepad, no new lines. New lines present when visualised with VisualStudio 2015. Seems to be an issue of the new line char sequence you used and how each application interprets that char sequence. I think the safest sequence would be \r\n, but I may be wrong.

**Comment by nelsonic** [comment]
@Starless2001 this is more of a Windows Notepad issue ... http://superuser.com/questions/362087/notepad-ignoring-linebreaks

We would accept a Pull Request if you have time, otherwise, go with an editor that _understands_ `\r` ...

The main question is: were you _able_ to use this in your code/project/task ? 😃

**Comment by Starless2001** [comment]
Yes, thank you. It is helping me a lot with a little pet project that would be impossible without this.

**Comment by nelsonic** [comment]
Sweet! 🍭  🚀
