### ISSUE TITLE
While downloading raw chrome ends up blocking the file 

### ISSUE THREAD

**Issue by Snktheone** [dwyl/english-words#34]
The file while downloading from Raw ends up being blocked as it mentions translating from Somali ?

**Comment by tomprogers** [comment]
I can't speak for the maintainers, but this issue isn't caused by the word list, it's caused by Chrome.

As far as workarounds, off the top of my head:

- try using right-click to Save File As instead of just opening it directly in a browser
- download the corresponding ZIP file instead of the raw text
- try a different browser, or use a command-line tool like curl

If none of those work, please provide some more information about the specific steps, as well as the exact text of the error message and I'll see what can be done.

**Comment by Snktheone** [comment]
Thanks Tom..appreciated downloading by zip fixed it
