### ISSUE TITLE
How to quickly import alpha in a database?

### ISSUE THREAD

**Issue by elnath78** [dwyl/english-words#85]
I have a test table open using Workbench, there is no way I can copy/paste the .txt file and auto populate the table?

**Comment by elnath78** [comment]
found this tool (https://nimbletext.com/Live) but maybe there is a better way?

**Comment by ndeoligence** [comment]
I think it depends on how you'd like to accomplish this. And whether you'll probably do it each time the words are updated. Do you know how to write code? Are you looking for advice with that route? Language?

Otherwise, I'd just copy the text and paste it into an sql insert. Text editors like atom have a multi-cursor tool which allows you to paste multiple lines (ie, all words) into a column.

But the latter option you might need to truncate the table and redo the process when there are changes. Or only write a script then. But it's pretty difficult elaborating on an option when I'm not sure what exactly you want

**Comment by elnath78** [comment]
> I think it depends on how you'd like to accomplish this.

I has used the above website to generate various `INSERT INTO` statement, but it was really slow, so I wrote a simple PHP script and launched it from SSH, in a few seconds it imported everything.
